### ISSUE TITLE
Sidebar fixed to bottom of screen

### ISSUE THREAD

**Issue by tareiking** [tareq1988/wedocs#2]
Notice on http://docs.wedevs.com/page-templates/
![image](https://cloud.githubusercontent.com/assets/687789/2589494/072ba0ae-ba4d-11e3-8821-09ff5939bd34.png)

**Comment by status201** [comment]
Can be fixed by adding relative max-height and overflow-y to the sidebar.
e.g. in your child theme css:
```css
.bs-sidebar {
	max-height: 80%; /* fallback for old browsers */
	max-height: calc(100% - 220px); /* adjust 220px to meet your website's header height*/
	overflow-y: auto;
}
```

alternatively you could let the sidebar disappear under the footer when scrolling down the page :
```css
footer.content-info {
    z-index: 99;
    position: relative;	
}
```
